services:
  web:
    image: nginx:alpine
    ports:
      - '8731:80'
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
